sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '13'
install:
  - yarn --ignore-engines
script:
  - yarn lint
  - yarn test
  - yarn report-coverage
  - yarn coveralls
  - yarn build:production
  - yarn test:lib
after_success:
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  code_climate:
    repo_token: 92a98a45735cb2b26ebda02789cd66ecd4da322559f9e1a3b68f871d64315fc5
