sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '8'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run report-coverage
  - npm run coveralls
  - npm run build:production
  - npm run test:lib
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  code_climate:
    repo_token: 92a98a45735cb2b26ebda02789cd66ecd4da322559f9e1a3b68f871d64315fc5
